//LAYOUT
export const AUTH_USER = 'AUTH_USER';
export const TOAST_UPDATE = 'TOAST_UPDATE';

//FACEBOOK
export const FACEBOOK_LOGIN_START = 'FACEBOOK_LOGIN_START';
export const FACEBOOK_LOGIN_REQUEST = 'FACEBOOK_LOGIN_REQUEST';
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAILURE = 'FACEBOOK_LOGIN_FAILURE';

//FACEBOOK
export const GET_REVENUE_DATA_START = 'GET_REVENUE_DATA_START';
export const GET_REVENUE_DATA_REQUEST = 'GET_REVENUE_DATA_REQUEST';
export const GET_REVENUE_DATA_SUCCESS = 'GET_REVENUE_DATA_SUCCESS';
export const GET_REVENUE_DATA_FAILURE = 'GET_REVENUE_DATA_FAILURE';
export const RESET_REVENUE_DATA = 'RESET_REVENUE_DATA';

//RESET
export const LOGOUT = 'LOGOUT';
export const RESET_AUTH = 'RESET_AUTH';
